# Generated by Django 2.2 on 2019-06-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='When did it happen')),
                ('what', models.CharField(help_text='What happened', max_length=500)),
            ],
        ),
    ]
