# Generated by Django 2.2 on 2019-06-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book', max_length=100)),
                ('ISBN', models.CharField(help_text='ISBN of the book, format: xx-xxxxx-xx-x OR yyy-yy-yyyy-yyy-y', max_length=17)),
                ('year', models.PositiveSmallIntegerField(help_text='Year of book release')),
                ('genre', models.CharField(choices=[('FAN', 'Fantasy'), ('SF', 'Science Fiction'), ('WEST', 'Western'), ('ROM', 'Romance'), ('THR', 'Thriller'), ('MYST', 'Mystery'), ('DS', 'Detective Story'), ('MEM', 'Memoir'), ('BIO', 'Biography'), ('PLAY', 'Play'), ('MUS', 'Musical'), ('SAT', 'Satire'), ('HAIKU', 'Haiku'), ('HOR', 'Horror'), ('DIY', 'DIY'), ('DICT', 'Dictionary')], default='Undefined', help_text='Genre of the book', max_length=20)),
                ('cover', models.CharField(help_text="URL of books' cover image", max_length=300, null=True)),
                ('numberOfAvailable', models.PositiveSmallIntegerField(help_text='Number of available books')),
                ('author', models.ForeignKey(help_text='Author of the book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Author')),
                ('publisher', models.ForeignKey(help_text='Publisher of the book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='publishers.Publisher')),
            ],
        ),
    ]
