# Generated by Django 2.2 on 2019-06-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='numberAvailable',
            new_name='numberOfAvailable',
        ),
    ]
