# Generated by Django 2.2 on 2019-05-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, help_text='ISBN of the book, format: xx-xxxxx-xx-x OR yyy-yy-yyyy-yyy-y', max_length=17),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Author of the book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(help_text="URL of books' cover image", max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(help_text='Publisher of the book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='publishers.Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Title of the book', max_length=100),
        ),
    ]
