# Generated by Django 2.2 on 2019-06-07 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned', models.BooleanField(default=False, help_text='Returned or not')),
                ('charge', models.FloatField(default=0.0, help_text='Charge for not returning the book on time')),
                ('paid', models.BooleanField(default=False, help_text='Paid or not pain')),
                ('dateOfLoan', models.DateField(help_text='Date of loan')),
                ('dateOfPlannedReturn', models.DateField(help_text='Date of planned return')),
                ('dateOfReturn', models.DateField(help_text='Date of actual return', null=True)),
                ('book', models.ForeignKey(help_text='Book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Book')),
                ('user', models.ForeignKey(help_text='User who borrowed', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
