# Generated by Django 2.2 on 2019-06-06 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfLoan', models.DateField(help_text='Date of loan')),
                ('dateOfPlannedReturn', models.DateField(help_text='Date of planned return')),
                ('dateOfReturn', models.DateField(help_text='Date of actual return', null=True)),
                ('book', models.ForeignKey(help_text='Book', on_delete=django.db.models.deletion.PROTECT, to='books.Book')),
                ('user', models.ForeignKey(help_text='User who borrowed', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
